# 超参数配置
# 约定：顶层 = 固定（环境统一），train_config = 随机（agent 异质性）

# 股票池与数据质量
stock_pool:
  pool_type: test
  data_quality_threshold: 0.8

meta_seed: 42

# 节点 meta：由主机提供
# 【顶层 = 固定】
meta:
  start_year: 2010
  end_year: 2024
  earliest_year_month: [1997, 1]
  n: 5
  max_portfolios_num: 252
  env_config:
    sample_and_shuffle_seed: 42 # 证券采样和洗牌的种子，保证所有的节点都使用相同的证券采样和洗牌
    rl_end_year: 2020   # 强化学习结束年份，月份默认 12
    save_every_n_steps: 20     # 每 252 步保存一次模型
  performance_config:
    risk_free_rate: 0.00
    rolling_window: 24
    std_window: 24

  # 【train_config = 随机】下面为 range/选项，由 node_manager 随机采样
  train_config:
    seed_range: [1, 1000] # [1, 1000]
    m_range: [12, 12] # [1, 12]
    mask_len_range: [88, 88] # [44, 88]
    model_config:
      cate_type: [0]
      dropout_range: [0.00, 0.25]
      # config 按 cate 选择
    reinforcement_config:
      cate: [0]
      lr_range: [1e-5, 1e-3]
      clip_grad_norm_range: [0.5, 1.0]
      weight_decay_range: [0, 0.01]
    reward_config:
      rtr_range: [0.1, 0.9]        # rtr 权重范围
      vol_range: [0.1, 0.9]        # vol 权重范围
      sharpe_range: [0.1, 0.9]     # sharpe 权重范围
      max_drawdown_range: [0.1, 0.9]  # max_drawdown 权重范围

# redis 数据冗余配置
redis_redundancy:
  interval: 5
  min_periods_year: 1
  max_periods_year: 3

# redis 数据过期配置
redis_expiration:
  interval: 5
  clean_up_threshold: 0.85
  clean_up_countdown: 300
