stock_pool:
  pool_type: balance_and_clean
  increment: 2014
  mask_start_year: null # 开始年份掩码
  data_filter:
    exclude_st: true
    exclude_fin: true
  data_quality_threshold: 0.8
  segment_num: 2
  segment_cursor: 2
  segment_seed: 43
meta_seed: 396
meta:
  checkpoint: true
  start_year: 2019
  end_year: 2024
  earliest_year_month:
  - 1997
  - 1
  n: 1
  max_portfolios_num: 5000
  short_limit: 0.0
  env_config:
    sample_and_shuffle_seed: 153
    rl_end_year: 2024
    save_model_every_n_steps: 7500
    save_record_every_n_steps: 6000
    save_performance_and_reward_every_n_steps: 7500
    box_max: 1
    box_min: -1
    retrain_times: 1
  performance_config:
    risk_free_rate: 0.0
    rolling_window: 24
    std_window: 24
    std_floor: 0.01
    classic_utility: true
  train_config:
    seed_range:
    - 1
    - 1000
    m_range:
    - 12
    - 12
    mask_len_range:
    - 60
    - 60
    model_config:
      cate_type:
      - 0
      dropout_range:
      - 0.25
      - 0.25
      tcn_config:
        num_channels_range:
        - 32
        - 128
        num_channels_len_range:
        - 1
        - 3
        kernel_size_options:
        - 3
        - 5
        - 7
      lstm_config:
        hidden_size_range:
        - 32
        - 128
        num_layers_range:
        - 1
        - 3
        bidirectional_options:
        - true
        - false
    reinforcement_config:
      cate:
      - 0
      lr_range:
      - 5e-4
      - 5e-4
      clip_grad_norm_range:
      - 0.5
      - 0.5
      weight_decay_range:
      - 0.1
      - 0.1
    reward_config:
      rtr_range:
      - 1
      - 1
      vol_range:
      - 0
      - 0
      sharpe_range:
      - 0
      - 0
      max_drawdown_range:
      - 0
      - 0
      diversification_range:
      - 0
      - 0
      A:
      - 1
      - 0.16
redis_redundancy:
  interval: 30
  min_periods_year: 2
  max_periods_year: 4
redis_expiration:
  isolated_data_exp: 1200
  interval: 60
  clean_up_threshold: 1
  clean_up_countdown: 300
updater_retry:
  max_retries: 10
  retry_delay: 3
